export const address = {
  state: [
    { state: "서울", codeNm: "서울" },
    { state: "부산", codeNm: "부산" },
    { state: "대구", codeNm: "대구" },
    { state: "인천", codeNm: "인천" },
    { state: "광주", codeNm: "광주" },
    { state: "대전", codeNm: "대전" },
    { state: "울산", codeNm: "울산" },
    { state: "세종", codeNm: "세종" },
    { state: "경기", codeNm: "경기" },
    { state: "강원", codeNm: "강원" },
    { state: "충북", codeNm: "충북" },
    { state: "충남", codeNm: "충남" },
    { state: "전북", codeNm: "전북" },
    { state: "전남", codeNm: "전남" },
    { state: "경북", codeNm: "경북" },
    { state: "경남", codeNm: "경남" },
    { state: "제주", codeNm: "제주" },
  ],
  city: [
    { state: "서울", city: "110", codeNm: "종로구" },
    { state: "서울", city: "140", codeNm: "중구" },
    { state: "서울", city: "170", codeNm: "용산구" },
    { state: "서울", city: "200", codeNm: "성동구" },
    { state: "서울", city: "215", codeNm: "광진구" },
    { state: "서울", city: "230", codeNm: "동대문구" },
    { state: "서울", city: "260", codeNm: "중랑구" },
    { state: "서울", city: "290", codeNm: "성북구" },
    { state: "서울", city: "305", codeNm: "강북구" },
    { state: "서울", city: "320", codeNm: "도봉구" },
    { state: "서울", city: "350", codeNm: "노원구" },
    { state: "서울", city: "380", codeNm: "은평구" },
    { state: "서울", city: "410", codeNm: "서대문구" },
    { state: "서울", city: "440", codeNm: "마포구" },
    { state: "서울", city: "470", codeNm: "양천구" },
    { state: "서울", city: "500", codeNm: "강서구" },
    { state: "서울", city: "530", codeNm: "구로구" },
    { state: "서울", city: "545", codeNm: "금천구" },
    { state: "서울", city: "560", codeNm: "영등포구" },
    { state: "서울", city: "590", codeNm: "동작구" },
    { state: "서울", city: "620", codeNm: "관악구" },
    { state: "서울", city: "650", codeNm: "서초구" },
    { state: "서울", city: "680", codeNm: "강남구" },
    { state: "서울", city: "710", codeNm: "송파구" },
    { state: "서울", city: "740", codeNm: "강동구" },
    { state: "부산", city: "110", codeNm: "중구" },
    { state: "부산", city: "140", codeNm: "서구" },
    { state: "부산", city: "170", codeNm: "동구" },
    { state: "부산", city: "200", codeNm: "영도구" },
    { state: "부산", city: "230", codeNm: "부산진구" },
    { state: "부산", city: "260", codeNm: "동래구" },
    { state: "부산", city: "290", codeNm: "남구" },
    { state: "부산", city: "320", codeNm: "북구" },
    { state: "부산", city: "350", codeNm: "해운대구" },
    { state: "부산", city: "380", codeNm: "사하구" },
    { state: "부산", city: "410", codeNm: "금정구" },
    { state: "부산", city: "440", codeNm: "강서구" },
    { state: "부산", city: "470", codeNm: "연제구" },
    { state: "부산", city: "500", codeNm: "수영구" },
    { state: "부산", city: "530", codeNm: "사상구" },
    { state: "부산", city: "710", codeNm: "기장군" },
    { state: "대구", city: "110", codeNm: "중구" },
    { state: "대구", city: "140", codeNm: "동구" },
    { state: "대구", city: "170", codeNm: "서구" },
    { state: "대구", city: "200", codeNm: "남구" },
    { state: "대구", city: "230", codeNm: "북구" },
    { state: "대구", city: "260", codeNm: "수성구" },
    { state: "대구", city: "290", codeNm: "달서구" },
    { state: "대구", city: "710", codeNm: "달성군" },
    { state: "인천", city: "110", codeNm: "중구" },
    { state: "인천", city: "114", codeNm: "중구영종출장소" },
    { state: "인천", city: "118", codeNm: "중구용유출장소" },
    { state: "인천", city: "140", codeNm: "동구" },
    { state: "인천", city: "177", codeNm: "미추홀구" },
    { state: "인천", city: "185", codeNm: "연수구" },
    { state: "인천", city: "200", codeNm: "남동구" },
    { state: "인천", city: "237", codeNm: "부평구" },
    { state: "인천", city: "245", codeNm: "계양구" },
    { state: "인천", city: "260", codeNm: "서구" },
    { state: "인천", city: "265", codeNm: "서구검단출장" },
    { state: "인천", city: "710", codeNm: "강화군" },
    { state: "인천", city: "720", codeNm: "옹진군" },
    { state: "광주", city: "110", codeNm: "동구" },
    { state: "광주", city: "140", codeNm: "서구" },
    { state: "광주", city: "155", codeNm: "남구" },
    { state: "광주", city: "170", codeNm: "북구" },
    { state: "광주", city: "200", codeNm: "광산구" },
    { state: "대전", city: "110", codeNm: "동구" },
    { state: "대전", city: "140", codeNm: "중구" },
    { state: "대전", city: "170", codeNm: "서구" },
    { state: "대전", city: "200", codeNm: "유성구" },
    { state: "대전", city: "230", codeNm: "대덕구" },
    { state: "울산", city: "110", codeNm: "중구" },
    { state: "울산", city: "140", codeNm: "남구" },
    { state: "울산", city: "170", codeNm: "동구" },
    { state: "울산", city: "200", codeNm: "북구" },
    { state: "울산", city: "710", codeNm: "울주군" },
    { state: "세종", city: "110", codeNm: "세종" },
    { state: "경기", city: "110", codeNm: "수원시" },
    { state: "경기", city: "111", codeNm: "수원시 장안구" },
    { state: "경기", city: "113", codeNm: "수원시 권선구" },
    { state: "경기", city: "115", codeNm: "수원시 팔달구" },
    { state: "경기", city: "117", codeNm: "수원시 영통구" },
    { state: "경기", city: "130", codeNm: "성남시" },
    { state: "경기", city: "131", codeNm: "성남시 수정구" },
    { state: "경기", city: "133", codeNm: "성남시 중원구" },
    { state: "경기", city: "135", codeNm: "성남시 분당구" },
    { state: "경기", city: "150", codeNm: "의정부시" },
    { state: "경기", city: "170", codeNm: "안양시" },
    { state: "경기", city: "171", codeNm: "안양시 만안구" },
    { state: "경기", city: "173", codeNm: "안양시 동안구" },
    { state: "경기", city: "190", codeNm: "부천시" },
    { state: "경기", city: "210", codeNm: "광명시" },
    { state: "경기", city: "220", codeNm: "평택시" },
    { state: "경기", city: "222", codeNm: "송탄출장소" },
    { state: "경기", city: "224", codeNm: "안중출장소" },
    { state: "경기", city: "250", codeNm: "동두천시" },
    { state: "경기", city: "270", codeNm: "안산시" },
    { state: "경기", city: "271", codeNm: "안산시 상록구" },
    { state: "경기", city: "273", codeNm: "안산시 단원구" },
    { state: "경기", city: "280", codeNm: "고양시" },
    { state: "경기", city: "281", codeNm: "고양시 덕양구" },
    { state: "경기", city: "285", codeNm: "고양시 일산동구" },
    { state: "경기", city: "287", codeNm: "고양시 일산서구" },
    { state: "경기", city: "290", codeNm: "과천시" },
    { state: "경기", city: "310", codeNm: "구리시" },
    { state: "경기", city: "360", codeNm: "남양주시" },
    { state: "경기", city: "362", codeNm: "풍양출장소" },
    { state: "경기", city: "370", codeNm: "오산시" },
    { state: "경기", city: "390", codeNm: "시흥시" },
    { state: "경기", city: "410", codeNm: "군포시" },
    { state: "경기", city: "430", codeNm: "의왕시" },
    { state: "경기", city: "450", codeNm: "하남시" },
    { state: "경기", city: "460", codeNm: "용인시" },
    { state: "경기", city: "461", codeNm: "용인시 처인구" },
    { state: "경기", city: "463", codeNm: "용인시 기흥구" },
    { state: "경기", city: "465", codeNm: "용인시 수지구" },
    { state: "경기", city: "480", codeNm: "파주시" },
    { state: "경기", city: "500", codeNm: "이천시" },
    { state: "경기", city: "550", codeNm: "안성시" },
    { state: "경기", city: "570", codeNm: "김포시" },
    { state: "경기", city: "590", codeNm: "화성시" },
    { state: "경기", city: "592", codeNm: "화성시동부출장소" },
    { state: "경기", city: "594", codeNm: "화성시동탄출장소" },
    { state: "경기", city: "610", codeNm: "광주시" },
    { state: "경기", city: "630", codeNm: "양주시" },
    { state: "경기", city: "650", codeNm: "포천시" },
    { state: "경기", city: "670", codeNm: "여주시" },
    { state: "경기", city: "800", codeNm: "연천군" },
    { state: "경기", city: "820", codeNm: "가평군" },
    { state: "경기", city: "830", codeNm: "양평군" },
    { state: "강원", city: "110", codeNm: "춘천시" },
    { state: "강원", city: "130", codeNm: "원주시" },
    { state: "강원", city: "150", codeNm: "강릉시" },
    { state: "강원", city: "170", codeNm: "동해시" },
    { state: "강원", city: "190", codeNm: "태백시" },
    { state: "강원", city: "210", codeNm: "속초시" },
    { state: "강원", city: "230", codeNm: "삼척시" },
    { state: "강원", city: "720", codeNm: "홍천군" },
    { state: "강원", city: "730", codeNm: "횡성군" },
    { state: "강원", city: "750", codeNm: "영월군" },
    { state: "강원", city: "760", codeNm: "평창군" },
    { state: "강원", city: "770", codeNm: "정선군" },
    { state: "강원", city: "780", codeNm: "철원군" },
    { state: "강원", city: "790", codeNm: "화천군" },
    { state: "강원", city: "800", codeNm: "양구군" },
    { state: "강원", city: "810", codeNm: "인제군" },
    { state: "강원", city: "820", codeNm: "고성군" },
    { state: "강원", city: "830", codeNm: "양양군" },
    { state: "충북", city: "110", codeNm: "청주시" },
    { state: "충북", city: "111", codeNm: "청주시 상당구" },
    { state: "충북", city: "112", codeNm: "청주시 서원구" },
    { state: "충북", city: "113", codeNm: "청주시 흥덕구" },
    { state: "충북", city: "114", codeNm: "청주시 청원구" },
    { state: "충북", city: "130", codeNm: "충주시" },
    { state: "충북", city: "150", codeNm: "제천시" },
    { state: "충북", city: "720", codeNm: "보은군" },
    { state: "충북", city: "730", codeNm: "옥천군" },
    { state: "충북", city: "740", codeNm: "영동군" },
    { state: "충북", city: "745", codeNm: "증평군" },
    { state: "충북", city: "750", codeNm: "진천군" },
    { state: "충북", city: "760", codeNm: "괴산군" },
    { state: "충북", city: "770", codeNm: "음성군" },
    { state: "충북", city: "800", codeNm: "단양군" },
    { state: "충남", city: "130", codeNm: "천안시" },
    { state: "충남", city: "131", codeNm: "천안시 동남구" },
    { state: "충남", city: "133", codeNm: "천안시 서북구" },
    { state: "충남", city: "150", codeNm: "공주시" },
    { state: "충남", city: "180", codeNm: "보령시" },
    { state: "충남", city: "200", codeNm: "아산시" },
    { state: "충남", city: "210", codeNm: "서산시" },
    { state: "충남", city: "230", codeNm: "논산시" },
    { state: "충남", city: "250", codeNm: "계룡시" },
    { state: "충남", city: "270", codeNm: "당진시" },
    { state: "충남", city: "710", codeNm: "금산군" },
    { state: "충남", city: "760", codeNm: "부여군" },
    { state: "충남", city: "770", codeNm: "서천군" },
    { state: "충남", city: "790", codeNm: "청양군" },
    { state: "충남", city: "800", codeNm: "홍성군" },
    { state: "충남", city: "810", codeNm: "예산군" },
    { state: "충남", city: "825", codeNm: "태안군" },
    { state: "전북", city: "110", codeNm: "전주시" },
    { state: "전북", city: "111", codeNm: "전주시 완산구" },
    { state: "전북", city: "113", codeNm: "전주시 덕진구" },
    { state: "전북", city: "118", codeNm: "전주시효자출" },
    { state: "전북", city: "130", codeNm: "군산시" },
    { state: "전북", city: "140", codeNm: "익산시" },
    { state: "전북", city: "145", codeNm: "익산시함열출" },
    { state: "전북", city: "180", codeNm: "정읍시" },
    { state: "전북", city: "190", codeNm: "남원시" },
    { state: "전북", city: "210", codeNm: "김제시" },
    { state: "전북", city: "710", codeNm: "완주군" },
    { state: "전북", city: "720", codeNm: "진안군" },
    { state: "전북", city: "730", codeNm: "무주군" },
    { state: "전북", city: "740", codeNm: "장수군" },
    { state: "전북", city: "750", codeNm: "임실군" },
    { state: "전북", city: "770", codeNm: "순창군" },
    { state: "전북", city: "790", codeNm: "고창군" },
    { state: "전북", city: "800", codeNm: "부안군" },
    { state: "전남", city: "110", codeNm: "목포시" },
    { state: "전남", city: "130", codeNm: "여수시" },
    { state: "전남", city: "150", codeNm: "순천시" },
    { state: "전남", city: "170", codeNm: "나주시" },
    { state: "전남", city: "230", codeNm: "광양시" },
    { state: "전남", city: "710", codeNm: "담양군" },
    { state: "전남", city: "720", codeNm: "곡성군" },
    { state: "전남", city: "730", codeNm: "구례군" },
    { state: "전남", city: "770", codeNm: "고흥군" },
    { state: "전남", city: "780", codeNm: "보성군" },
    { state: "전남", city: "790", codeNm: "화순군" },
    { state: "전남", city: "800", codeNm: "장흥군" },
    { state: "전남", city: "810", codeNm: "강진군" },
    { state: "전남", city: "820", codeNm: "해남군" },
    { state: "전남", city: "830", codeNm: "영암군" },
    { state: "전남", city: "840", codeNm: "무안군" },
    { state: "전남", city: "860", codeNm: "함평군" },
    { state: "전남", city: "870", codeNm: "영광군" },
    { state: "전남", city: "880", codeNm: "장성군" },
    { state: "전남", city: "890", codeNm: "완도군" },
    { state: "전남", city: "900", codeNm: "진도군" },
    { state: "전남", city: "910", codeNm: "신안군" },
    { state: "경북", city: "110", codeNm: "포항시" },
    { state: "경북", city: "111", codeNm: "포항시 남구" },
    { state: "경북", city: "113", codeNm: "포항시 북구" },
    { state: "경북", city: "130", codeNm: "경주시" },
    { state: "경북", city: "150", codeNm: "김천시" },
    { state: "경북", city: "170", codeNm: "안동시" },
    { state: "경북", city: "190", codeNm: "구미시" },
    { state: "경북", city: "210", codeNm: "영주시" },
    { state: "경북", city: "230", codeNm: "영천시" },
    { state: "경북", city: "250", codeNm: "상주시" },
    { state: "경북", city: "280", codeNm: "문경시" },
    { state: "경북", city: "290", codeNm: "경산시" },
    { state: "경북", city: "720", codeNm: "군위군" },
    { state: "경북", city: "730", codeNm: "의성군" },
    { state: "경북", city: "750", codeNm: "청송군" },
    { state: "경북", city: "760", codeNm: "영양군" },
    { state: "경북", city: "770", codeNm: "영덕군" },
    { state: "경북", city: "820", codeNm: "청도군" },
    { state: "경북", city: "830", codeNm: "고령군" },
    { state: "경북", city: "840", codeNm: "성주군" },
    { state: "경북", city: "850", codeNm: "칠곡군" },
    { state: "경북", city: "900", codeNm: "예천군" },
    { state: "경북", city: "920", codeNm: "봉화군" },
    { state: "경북", city: "930", codeNm: "울진군" },
    { state: "경북", city: "940", codeNm: "울릉군" },
    { state: "경남", city: "120", codeNm: "창원시" },
    { state: "경남", city: "121", codeNm: "창원시 의창구" },
    { state: "경남", city: "123", codeNm: "창원시 성산구" },
    { state: "경남", city: "125", codeNm: "창원시 마산합포구" },
    { state: "경남", city: "127", codeNm: "창원시 마산회원구" },
    { state: "경남", city: "129", codeNm: "창원시 진해구" },
    { state: "경남", city: "170", codeNm: "진주시" },
    { state: "경남", city: "220", codeNm: "통영시" },
    { state: "경남", city: "240", codeNm: "사천시" },
    { state: "경남", city: "245", codeNm: "사천남양출장" },
    { state: "경남", city: "250", codeNm: "김해시" },
    { state: "경남", city: "252", codeNm: "장유출장소" },
    { state: "경남", city: "270", codeNm: "밀양시" },
    { state: "경남", city: "310", codeNm: "거제시" },
    { state: "경남", city: "330", codeNm: "양산시" },
    { state: "경남", city: "332", codeNm: "양산시웅상출장소" },
    { state: "경남", city: "720", codeNm: "의령군" },
    { state: "경남", city: "730", codeNm: "함안군" },
    { state: "경남", city: "740", codeNm: "창녕군" },
    { state: "경남", city: "820", codeNm: "고성군" },
    { state: "경남", city: "840", codeNm: "남해군" },
    { state: "경남", city: "850", codeNm: "하동군" },
    { state: "경남", city: "860", codeNm: "산청군" },
    { state: "경남", city: "870", codeNm: "함양군" },
    { state: "경남", city: "880", codeNm: "거창군" },
    { state: "경남", city: "890", codeNm: "합천군" },
    { state: "제주", city: "110", codeNm: "제주시" },
    { state: "제주", city: "130", codeNm: "서귀포시" },
  ],
};
